services:
  database:
    image: postgres
    container_name: erp_database
    restart: always
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - erp_network

  backend:
    build:
      context: ./
    container_name: erp_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - erp_network

networks:
  erp_network:
    driver: bridge

volumes:
  database:
    name: erp_database
