spring:
  application:
    name: erp-api
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://erp_database:3306/erp
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
  servlet:
    multipart:
      max-request-size: 10485760
      max-file-size: 10485760

file-extensions-config:
  allowed-extensions: jpg,jpeg,png,bmp
