spring:
  application:
    name: erp-api
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:erp
    username: default_user
    password: 12345
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: off
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
  servlet:
    multipart:
      max-request-size: 10485760
      max-file-size: 10485760
